language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-hxlib' ]; then cd .. && eval "mv $currentfolder generator-hxlib" && cd generator-hxlib; fi

