language: node_js
node_js:
- '0.10'

notifications:
    irc:
        - "chat.freenode.net#dropecho"

deploy:
  provider: npm
  email: vantreeseba@gmail.com
  api_key:
    secure: UfP5w0sWh6tGo+RDfoEfnfQ95CrjzxEllw9+P/fapyUXS8wnnhS3UBGtNfdPpFSPxvMG18KwBKuyK/nJEK0jvGpDOXcO6inlENvP/1zQMDVBe3gZwgm6PylfI2lPdM0QoBS0u+F0XoRmnDcyDHgc4SUm6kGLubzmAA7gZomoY4A=
  on:
    branch: master
    tags: true
